spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskflow_db
    username: root
    password: MySql@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect

app: 
  security:
    jwt:
      secret-key: wicnsheire7ea9323453scre73fffeac
      expiration: 86400000
    cors: 
      allowed-origins:
        - http://localhost:5173